### ISSUE TITLE
Geometry outputs as [object object] in table views

### ISSUE THREAD

**Issue by yochannah** [afrimapr/afrimapr_dev#5]
Hey folks,

Not sure if this is the right place to log this, but I noticed in the healthsites viewer and the south africa beds deployments that there is a little bug (I think?) in the geometry data columns, where it's outputting a classic javascript `[Object object]` instead of a value. I'm not sure what this should actually output like, perhaps lat/lon or some sort of shape info? 

![image](https://user-images.githubusercontent.com/9271438/96857201-9e450b00-1456-11eb-9d3d-dde4db162920.png)

**Comment by andysouth** [comment]
Thanks @yochannah , well spotted, you are quite right. This happens because the R sf package stores the coordinates of the polygons in the geometry column. What we should do (and I will) is to exclude that column in the tables.

**Comment by andysouth** [comment]
Should be fixed now :-)
